### ISSUE TITLE
Request: episode naming

### ISSUE THREAD

**Issue by ReenigneArcher** [jmichas/PlexTrainingVideoScannerAndAgent#15]
Is this still maintained, specifically, the series scanner?

I'd like to use this for videos named like so: `TV Root\Show Name\Season Name\Episode Name (video_id).ext`

Note there's no episode number. If it's a problem to add this could you let me know which lines of code to look at?

P.S. How do I get it to log in the default plug ins log folder, without hard coding the path?

**Comment by jmichas** [comment]
I'm sorry to say it hasn't been touched for some time now. I don't really have the time or the need to work on it. It was a hobby project and there is so little documentation on the custom scanner, or at least there was very little when I wrote it, that it made it painful to work on.

I had to hard code the path for the logs because I couldn't figure out how to make a new field in settings so you could set it from within plex. Like I said, there was no documentation so I did what I could.

I don't recall where the code is but you are looking for a bunch of regex statements, you would need to add you custom naming scheme as a new pattern to match. It shouldn't be too difficult but its a pain to test.

Good luck.
